# Generated by Django 3.0.5 on 2020-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_pet_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='type',
            field=models.CharField(default='', max_length=70),
        ),
    ]
